#!/usr/bin/env bash

theme="~/.config/rofi/powermenu.rasi"
icons=(shutdown '⏻' reboot '󰑓' hibernate '' lock '' suspend '' logout '󰍃' yes '' no '')
declare -A iconMap
for ((i = 0; i < ${#icons[@]}; i += 2)); do
    iconMap[${icons[i]}]=${icons[i+1]}
done

uptime=$(uptime -p | sed -e 's/up //g')
host=$(cat /etc/hostname)

rofi_cmd() {
    echo -e "${iconMap[lock]}\n${iconMap[suspend]}\n${iconMap[logout]}\n${iconMap[hibernate]}\n${iconMap[reboot]}\n${iconMap[shutdown]}" | rofi -dmenu -p " $USER@$host" -mesg " Uptime: $uptime" -theme ${theme}
}

confirm_cmd() {
    echo -e "${iconMap[yes]}\n${iconMap[no]}" | rofi -dmenu -p 'Confirmation' -mesg 'Are you Sure?' -theme ${theme} \
        -theme-str 'window {location: center; anchor: center; fullscreen: false; width: 350px;}' \
        -theme-str 'mainbox {children: [ "message", "listview" ];}' \
        -theme-str 'listview {columns: 2; lines: 1;}' \
        -theme-str 'element-text {horizontal-align: 0.5;}' \
        -theme-str 'textbox {horizontal-align: 0.5;}'
}

execute_command() {
    local selected=$1
    case $selected in
        "${iconMap[shutdown]}") systemctl poweroff ;;
        "${iconMap[reboot]}") systemctl reboot ;;
        "${iconMap[hibernate]}") systemctl hibernate ;;
        "${iconMap[suspend]}")
            mpc -q pause
            amixer set Master mute
            systemctl suspend
            ;;
        "${iconMap[logout]}")
            case "$DESKTOP_SESSION" in
                openbox) openbox --exit ;;
                bspwm) bspc quit ;;
                i3) i3-msg exit ;;
                plasma) qdbus org.kde.ksmserver /KSMServer logout 0 0 0 ;;
                qtile) qtile cmd-obj -o cmd -f shutdown ;;
            esac
            ;;
        "${iconMap[lock]}")
            [[ -x '/usr/bin/betterlockscreen' ]] && betterlockscreen -l
            ;;
    esac
}

chosen=$(rofi_cmd)
[[ -z "$chosen" ]] && exit 0
if [[ "$chosen" != "${iconMap[lock]}" ]]; then
    confirmed=$(confirm_cmd)
    [[ "$confirmed" == "${iconMap[yes]}" ]] && execute_command "$chosen"
else
    execute_command "$chosen"
fi

